# Generated by Django 5.1.1 on 2024-09-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadeveiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
