# Generated by Django 5.1.1 on 2024-09-09 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaDeVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('pago', models.BooleanField(default=False)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.entradadeveiculo')),
            ],
        ),
    ]
